apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo
data:
  SPRING_PROFILES_ACTIVE: production
  SERVER_PORT: "8080"
  DB_HOST: mysql.example.internal
  DB_PORT: "3306"
  DB_NAME: todo_db
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
